default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # database: cookbook_db_rdz2
  # username: cookbook_db_rdz2_user
  # password: IrPp9YNotqEhCDMNuCxJgEWU6PGG0ulC
  # host: dpg-csltmfdumphs73as57rg-a
  # port: 5432


