default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 192.168.0.121
  username: DATABASE_USERNAME
  password: DATABASE_PASSWORD

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE'] %>
  
